### ISSUE TITLE
Windows Anaconda Error

### ISSUE THREAD

**Issue by Jalmood** [creotiv/object_detection_projects#4]
When I try it with small video file its saved images in out folder and write csv file.
But in the end this error show up:
```
Traceback (most recent call last):
  File "C:\Users\Dev-PC\Anaconda3\envs\Cars\lib\site-packages\skvideo\io\ffmpeg.py", line 267, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "traffic.py", line 115, in <module>
    main()
  File "traffic.py", line 80, in main
    for frame in cap:
  File "C:\Users\Dev-PC\Anaconda3\envs\Cars\lib\site-packages\skvideo\io\io.py", line 253, in vreader
    for frame in reader.nextFrame():
  File "C:\Users\Dev-PC\Anaconda3\envs\Cars\lib\site-packages\skvideo\io\ffmpeg.py", line 293, in nextFrame
    yield self._readFrame()
  File "C:\Users\Dev-PC\Anaconda3\envs\Cars\lib\site-packages\skvideo\io\ffmpeg.py", line 277, in _readFrame
    s = self._read_frame_data()
  File "C:\Users\Dev-PC\Anaconda3\envs\Cars\lib\site-packages\skvideo\io\ffmpeg.py", line 271, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
```

**Comment by creotiv** [comment]
Running Python code on Windows is a very very bad idea, especially DS
code.
And i dont using it for development, so sorry but can't help.


Kindly yours,
Andrey Nikishaev

Sit&Fit <https://angel.co/sit-fit/> - underdesk stepper trainer.
Essenly <http://essenly.com> - книги в кратком изложении.
groovyCV <http://groovycv.com> - создание стильных резюме

Rates         Soft Dev from $40/h, Consultation BizDev/Marketing/Customer
Rel/IT from $80/h
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666
